### PR TITLE
CUS4-34: Add subject for overdue balance payments.

### PR DESCRIPTION
**Pull request by davidsbond**
Adds the subject that will be used by customer-billing platform for tracking
overdue payments.

### CODE REVIEW

**Review by oliverpauffley — APPROVED** [review]
It seems odd that review this? is that right?

**Comment by davidsbond** [comment]
@oliverpauffley, sorry not sure what you're asking? 

Part of the instructions for working with click is that if you want tracking in mixpanel you have to use a subject/intent that's referenced from these protos:

https://github.com/utilitywarehouse/click.uw.co.uk/blob/master/contract/api.proto#L52
https://github.com/utilitywarehouse/click.uw.co.uk#tracking-clicks

**Comment by oliverpauffley** [comment]
Nothing really. Not that we are doing the wrong thing just that we are creating something in another repo that isn't "owned" by us but its fine!

**Comment by davidsbond** [comment]
@oliverpauffley I think the idea is that this repo is shared since it's for every team that wants to perform any customer tracking. Similar to how unicom have a template repository everyone uses.

**Pull request merged**
